# Q3
# This query is a deadlock for the old engine. The new finishes in ~5 sec.
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ub: <http://uob.iodt.ibm.com/univ-bench-dl.owl#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#> 

SELECT *
WHERE {
	?X ub:isAdvisedBy _:a .
	_:a ub:teacherOf ?Y .
	?X ub:takesCourse ?Y .
}
