# Q4
# This query retrieves no results.

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ub: <http://uob.iodt.ibm.com/univ-bench-dl.owl#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#> 

SELECT *
WHERE {
	?X ub:worksFor ?Y .
	?Y rdf:type ub:ResearchGroup .
	?X ub:takesCourse ?Z .
	?W ub:teacherOf ?Z .
}
